name: 🌍 Deploy Vite Portfolio via FTPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 🔨 Build Job
  build:
    name: build 
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@main

      - name: 🟢 Setup Node
        uses: actions/setup-node@main
        with:
          node-version: 20.x

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗️ Build Vite Project
        run: npm run build

      - name: ✅ Verify dist folder exists
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Dist folder not found! Did 'npm run build' fail?"
            exit 1
          fi
          echo "✅ Dist folder exists."

      - name: 📝 List dist files
        run: ls -R dist

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist

  # 🚀 Deploy Job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download Artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist

      - name: 🌍 Deploy to FTPS Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: "ftp.launit.com"
          REMOTE_USER: "info@launit.com"
          TARGET: "/new/"
          args: '--no-check-certificate'
